### ISSUE TITLE
Rotating map in drive

### ISSUE THREAD

**Issue by GaMsh** [fokin33/osmodroid#11]
Необходимо убрать поворот карты, если не включена текущая позиция (двигание карты за текущей позицией), а то выходит бред.

Логика такая:
включен поворот карты, двигаем пальцем (слежение прекратилось), угол фиксируется на том, который и был, если нажали снова "следить за позицией" - то поворот продолжиться вместе по слежением, а если нажали поворот, без слежения - всё также вернуть ориентацию на север.

**Comment by fokin33** [comment]
Вроде сделано
