### ISSUE TITLE
Update channel_chat

### ISSUE THREAD

**Issue by GaMsh** [fokin33/osmodroid#16]
Люди требуют следующие добавки для повышения удобства:
- выделять свои сообщения фоном (например светлосерым)
- выделять ники пользователей цветом (чтобы лучше различалось)
- сделать "обращения":
  - по тыку в сообщение не от себя - в строку отправки сообщения добавляется "Ник, " чтобы было удобней
  - если в присланном сообщении есть "Ник, ", где Ник = Текущий пользователь, то необходимо выделить это сообщение ярким фоном, и может другим типом уведомления/звуком...

**Comment by fokin33** [comment]
Примерно сделано как написано

**Comment by GaMsh** [comment]
Неее надо фоном. Цвет ника почти незаметен
