### ISSUE TITLE
Map - new for channel

### ISSUE THREAD

**Issue by GaMsh** [fokin33/osmodroid#17]
Добавки по каналам для раздела "Карта": 
- сделать отключаемыми "следы" за участниками (также можно учитывать настройки канала, там есть такой пункт)
- поворот карты, если возможно, можно перенести на "компас" в левом углу, то есть реакция на нажатие, и если ориентация на север компас как-то должен отличаться или "застывать" в положении на север соответственно.

**Comment by fokin33** [comment]
Сделано
