### ISSUE TITLE
Список участников канала

### ISSUE THREAD

**Issue by fokin33** [fokin33/osmodroid#20]
просят вернуть список пользователей, но стало логичней показывать активных. Итого некая кнопка на карте, нажав в которую вылещаёт "попап" со списком участников у кого active=1, с показом онлайн статуса цветом и расстоянием до них по прямой. По тыку в пользователя перемещение к нему на карте или сообщение в чат на его имя (выбор в контекстном меню).

**Comment by GaMsh** [comment]
В контексте новой системы, удобно было бы как то показывать онлайн людей и может с фильтрацией кто передаёт данные.
