### ISSUE TITLE
Start message

### ISSUE THREAD

**Issue by GaMsh** [fokin33/osmodroid#24]
Надо бы починить стартовое сообщение, а то только увидел - повернул телефон и более его никак не увидеть! Надо бы его локально сохранять и показывать всегда на главном экране. Может быть отделить какой-то полосой. И цветом выделить (цветом текста). Сообщение будет не всегда, потому его можно сделать ярким, так как планируется только для важных объявлений его использовать.

**Comment by fokin33** [comment]
Теперь всегда на экране.(только после получения нового сохранится)
